# Generated by Django 3.2.8 on 2021-10-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='about',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='form',
            name='address',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='form',
            name='date_of_bith',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='form',
            name='education',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.EmailField(default='None', max_length=254),
        ),
        migrations.AddField(
            model_name='form',
            name='language1',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='language2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='language3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='phone',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='form',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='form',
            name='previous_position',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AddField(
            model_name='form',
            name='skill1',
            field=models.CharField(default='None', max_length=80),
        ),
        migrations.AddField(
            model_name='form',
            name='skill2',
            field=models.CharField(default='None', max_length=80),
        ),
        migrations.AddField(
            model_name='form',
            name='skill3',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='form',
            name='skill4',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='form',
            name='skill5',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='form',
            name='skill6',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='form',
            name='surname',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
